[meta]
name = "ASR_CPU"
pretrained_path = "jonatasgrosman/wav2vec2-large-xlsr-53-italian"
seed = 42
epochs = 20
save_dir = "saved/"
gradient_accumulation_steps = 4
use_amp = false
device_ids = "None"
sr = 44100
max_clip_grad_norm = 5.0

[special_tokens]
bos_token = "<bos>"
eos_token = "<eos>"
unk_token = "<unk>"
pad_token = "<pad>"

[huggingface]
push_to_hub = false
push_every_validation_step = false
overwrite_output_dir = false
blocking = false

[huggingface.args]
local_dir = "my_ASR_model"
use_auth_token = false
clone_from = ""

[train_dataset]
path = "base.base_dataset.BaseDataset"

[train_dataset.args]
path = "/home/cristiano.chesi/pr_ppa/cleaned_audio_transcriptions_train.csv"
preload_data = false
delimiter = "|"
nb_workers = 4

[train_dataset.dataloader]
batch_size = 1
num_workers = 4
pin_memory = false
drop_last = true

[train_dataset.sampler]
shuffle = true
drop_last = true

[val_dataset]
path = "base.base_dataset.BaseDataset"

[val_dataset.args]
path = "/home/cristiano.chesi/pr_ppa/cleaned_audio_transcriptions_valid.csv"
preload_data = false
delimiter = "|"
nb_workers = 4

[val_dataset.dataloader]
batch_size = 1
num_workers = 2
pin_memory = false

[val_dataset.sampler]
shuffle = false
drop_last = false

[optimizer]
lr = 1e-6

[scheduler]
max_lr = 5e-4

[trainer]
path = "trainer.trainer.Trainer"

[trainer.args]
validation_interval = 500
save_max_metric_score = false
enable_memory_efficient = true
gradient_checkpointing = true